# Generated by Django 3.2 on 2022-07-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMvt', '0002_auto_20220705_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
            ],
        ),
    ]
